name: CI
on:
  push:
    branches:
      - main

jobs:
  # Builds for x64
  build_and_release_x64:
    runs-on: windows-latest
    permissions:
      # needed for releasing
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Build DLL (Release x64)
        run: msbuild BasicDLL.sln /p:Configuration=Release /p:Platform="x64"
        id: build_release_x64

      - name: Build DLL (Debug x64)
        run: msbuild BasicDLL.sln /p:Configuration=Debug /p:Platform="x64"
        id: build_debug_x64

      - name: Release DLL (Release x64)
        if: steps.build_release_x64.outcome == 'success'
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          automatic_release_tag: ${{github.sha}}
          title: Build for SHA "${{github.sha}}" (Release x64)
          files: |
            build/Release-x64/BasicDLL.dll
            build/Release-x64/BasicDLL.pdb
            build/Release-x64/intermediates/BasicDLL.log
          prerelease: false

      - name: Release DLL (Debug x64)
        if: steps.build_debug_x64.outcome == 'success'
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          automatic_release_tag: "refs/head/main"
          title: Build for SHA "${{github.sha}}" (Debug x64)
          files: |
            build/Debug-x64/BasicDLL.dll
            build/Debug-x64/BasicDLL.pdb
            build/Debug-x64/intermediates/BasicDLL.log
          prerelease: false

  # builds for Win32/x86
  build_and_release_Win32:
    runs-on: windows-latest
    permissions:
      # needed for releasing
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Build DLL (Release Win32)
        if: always ()
        run: msbuild BasicDLL.sln /p:Configuration=Release /p:Platform="x86"
        id: build_release_win32

      - name: Build DLL (Debug Win32)
        if: always ()
        run: msbuild BasicDLL.sln /p:Configuration=Debug /p:Platform="x86"
        id: build_debug_win32

      - name: Release DLL (Release Win32)
        if: steps.build_release_win32.outcome == 'success'
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          automatic_release_tag: ${{github.sha}}
          title: Build for SHA "${{github.sha}}" (Release Win32)
          files: |
            build/Release-Win32/BasicDLL.dll
            build/Release-Win32/BasicDLL.pdb
            build/Release-Win32/intermediates/BasicDLL.log
          prerelease: false

      - name: Release DLL (Debug Win32)
        if: steps.build_debug_win32.outcome == 'success'
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          automatic_release_tag: "refs/head/main"
          title: Build for SHA "${{github.sha}}" (Debug Win32)
          files: |
            build/Debug-Win32/BasicDLL.dll
            build/Debug-Win32/BasicDLL.pdb
            build/Debug-Win32/intermediates/BasicDLL.log
          prerelease: false
