name: CI
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Build DLL (Release)
        run: msbuild BasicDLL.sln /p:Configuration=Release

      - name: Build DLL (Debug)
        run: msbuild BasicDLL.sln /p:Configuration=Debug
  release:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - name: Release DLL (Release)
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          automatic_release_tag: ${{github.sha}}
          title: Build for SHA "${{github.sha}}" (Release)
          files: |
            build/Release-x64/BasicDLL.dll
            build/Release-x64/BasicDLL.pdb
            build/Release-x64/intermediates/BasicDLL.log
          prerelease: false

      - name: Release DLL (Debug)
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          automatic_release_tag: "refs/head/main"
          title: Build for SHA "${{github.sha}}" (Debug)
          files: |
            build/Debug-x64/BasicDLL.dll
            build/Debug-x64/BasicDLL.pdb
            build/Debug-x64/intermediates/BasicDLL.log
          prerelease: false
