name: CI
on:
  push:
    branches:
      - main

jobs:
  # Builds for x64
  build_and_release_x64:
    runs-on: windows-latest
    permissions:
      # needed for releasing
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Build DLL (Release x64)
        run: msbuild BasicDLL.sln /p:Configuration=Release /p:Platform="x64"

      - name: Build DLL (Debug x64)
        run: msbuild BasicDLL.sln /p:Configuration=Debug /p:Platform="x64"

      - name: Build DLL (Release Win32)
        run: msbuild BasicDLL.sln /p:Configuration=Release /p:Platform="x86"

      - name: Build DLL (Debug Win32)
        run: msbuild BasicDLL.sln /p:Configuration=Debug /p:Platform="x86"

      - name: ZIP the build folder
        run: powershell ./zip-build.ps1

      - name: Release DLL
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          automatic_release_tag: "auto_release"
          title: Build
          files: |
            ./build.zip
          prerelease: false
